/*    Copyright (c) 2014 Zuora, Inc.
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy of 
 *   this software and associated documentation files (the "Software"), to use copy, 
 *   modify, merge, publish the Software and to distribute, and sublicense copies of 
 *   the Software, provided no fee is charged for the Software.  In addition the
 *   rights specified above are conditioned upon the following:
 *
 *   The above copyright notice and this permission notice shall be included in all
 *   copies or substantial portions of the Software.
 *
 *   Zuora, Inc. or any other trademarks of Zuora, Inc.  may not be used to endorse
 *   or promote products derived from this Software without specific prior written
 *   permission from Zuora, Inc.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 *   ZUORA, INC. BE LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES
 *   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *   ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var ifrmId="z_hppm_iframe";var Z=function(){var g="#z-overlay {opacity:0.5;display:inline-block;position:fixed;top:0;left:0;width:100%;height:100%;background-color: #000;z-index: 1001;}";var d="#z-container {border:1px;float:left; overflow: visible; position: absolute;padding: 0px; display: inline-block; top:5%; left:34%; margin: 0 auto;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius:5px;background-color: #FAFAFA; border:1px solid #FAFAFA;border-top-color:#EDEDED;behavior: url(js/PIE.htc);z-index: 1002;}";var l="#z-data {height: 100%; outline: 0px; width: 100%; overflow: visible;display: inline-block;border:1px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius:5px;}";var i="#reset{*, *:before, *:after {display: inline-block;-webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;}}";var f="#z_hppm_iframe {background-color: #FAFAFA;vertical-align:bottom;z-index:9999;display:block;padding:0px;margin: 0px; border:0px solid #DDD;}";var a="requestPage";var j;var k,e,c;var h=["tenantId","id","token","signature","key","style","submitEnabled","url"];var b=["creditCardNumber","cardSecurityCode","creditCardExpirationYear","creditCardExpirationMonth"];return{validateRequiredParams:function(o){var m=h.length;for(index=0;index<m;index++){if(!o.hasOwnProperty(h[index])){if(h[index]=="submitEnabled"&&o.style.toLowerCase()=="overlay"){continue}else{var n="Param with key ["+h[index]+"] is required.";alert(n);if(!Z.isIE()){console.log(n)}return false}}}return true},isIE:function(){var o=window.navigator.userAgent;var n=o.indexOf("MSIE ");var m=o.indexOf("Trident/");if(n>0){return true}if(m>0){var q=o.indexOf("rv:");return true}return false},validatePCIParams:function(q){var m=b.length;for(index=0;index<m;index++){var n="field_"+b[index];if(q.hasOwnProperty(n)){if(0<q[n].trim().length&&q[n].trim().length<300){var o="Field ["+n+"] for Credit Card payment method type should be encrypted for pre-population";alert(o);if(!Z.isIE()){console.log(o)}return false}}}return true},init:function(o,q){k="?method=requestPage&host="+encodeURIComponent(document.location.href)+"&";
var n=Z.validateRequiredParams(o);if(!n){return false}n=Z.validatePCIParams(o);if(!n){return false}var m=JSON.stringify(o,function(r,s){if(r!=""){if("key"==r){c=decodeURIComponent(s)}else{if("url"==r){j=s}else{k=k+r+"="+s+"&"}}}return s});p=JSON.parse(m);ZXD.receiveMessage(function(s){var r=s.data;r=JSON.parse(r);if(r.success){if(q){q(r)}else{Z.responseHandler(r)}}else{if(r.success==false){Z.deactivateOverlay("z-overlay");Z.deactivateOverlay("z-container");q(r)}else{if(r.action=="close"){Z.deactivateOverlay("z-overlay");Z.deactivateOverlay("z-container")}else{if(r.action=="resize"){Z.receive(r)}else{Z.receive(r)}}}}});return true},prepopulate:function(o){var q=Z.createIframeURL();if(q==document.getElementById(ifrmId).src){var m=JSON.stringify(o,function(r,t){if(r!=""){var s="setField("+r+":"+t+")";Z.post(ifrmId,s)}return t});var n="setField(key:"+c+")";Z.post(ifrmId,n);Z.post(ifrmId,"setField(style:"+p.style+")");Z.post(ifrmId,"resize")}},render:function(s,u,t){var o=Z.init(s,t);if(!o){return}if(u&&u.creditCardCountry&&(u.creditCardCountry==="USA"||u.creditCardCountry==="CAN")){u.creditCardState=u.creditCardState||" "}e=u;var q=document.getElementById("zuora_payment");if(typeof q=="undefined"||!q){return{error:"invalid_request",error_description:"The container you specified does not exist"}}Z.cleanUp(q,"z-overlay");Z.cleanUp(q,"z-container");if(p.style=="inline"){Z.addInlineStyles();Z.createIframe(q);return}if(p.style=="overlay"){Z.addOverlayStyles();var n=Z.generateDiv("z-overlay","z-overlay");q.appendChild(n);var r=Z.generateDiv("z-container","z-container");q.appendChild(r);var m=Z.generateDiv("z-data","z-data");m.tabindex="-1";r.appendChild(m);Z.createIframe(document.getElementById("z-data"));Z.activateOverlay("z-overlay")}},cleanUp:function(n,m){var o=document.getElementById(m);if(o!=null){n.removeChild(o)}},activateOverlay:function(n){try{document.getElementById(n).style.display="inline"}catch(m){}},deactivateOverlay:function(n){try{document.getElementById(n).style.display="none"}catch(m){}},generateDiv:function(q,n,m){var o=document.createElement("div");
o.id=q;o.className=n;o.border="0";if(o.addEventListener){o.addEventListener("click",m,false)}else{o.attachEvent("click",m)}return o},addOverlayStyles:function(){var r=document.createElement("style");r.type="text/css";var n=document.createTextNode(g);var s=document.createTextNode(d);var m=document.createTextNode(l);var q=document.createTextNode(f);var o=document.createTextNode(i);if(r.styleSheet){r.styleSheet.cssText=n.nodeValue+" "+s.nodeValue+" "+m.nodeValue+" "+o.nodeValue+" "+q.nodeValue}else{r.appendChild(n);r.appendChild(s);r.appendChild(m);r.appendChild(q);r.appendChild(o)}document.getElementsByTagName("head")[0].appendChild(r)},addInlineStyles:function(){var n=document.createElement("style");n.type="text/css";var m=document.createTextNode(f);if(n.styleSheet){n.styleSheet.cssText=m.nodeValue}else{n.appendChild(m)}document.getElementsByTagName("head")[0].appendChild(n)},createIframe:function(m){var o=Z.createIframeURL();var n=document.createElement("iframe");n.setAttribute("src",o);n.setAttribute("id",ifrmId);n.setAttribute("overflow","visible");n.setAttribute("scrolling","no");n.setAttribute("frameBorder","0");n.setAttribute("allowtransparency","true");n.setAttribute("class","z_hppm_iframe");n.setAttribute("width","100%");n.setAttribute("height","100%");if(n.addEventListener){n.addEventListener("load",function(q){Z.prepopulate(e);return false},false)}else{n.attachEvent("onload",function(){Z.prepopulate(e);return false})}if(typeof options!="undefined"){if(typeof options.vertical!="undefined"&&options.vertical){n.style.width="100%";n.style.height="100%"}}m.appendChild(n)},createIframeURL:function(){var m=j;return m.concat(k)},post:function(o,n){var m=document.getElementById(o);var q=m.src+"#"+encodeURIComponent(document.location.href);m.src=q;ZXD.postMessage(n,q,m.contentWindow);return false},receive:function(m){ZFB.resizeCaller(ifrmId,m.action,m.height,m.width)},validate:function(){return document.getElementById(ifrmId).contentWindow.ZLT.validate()},submit:function(){var m=document.getElementById(ifrmId).src+"#"+encodeURIComponent(document.location.href);
document.getElementById(ifrmId).src=m;ZXD.postMessage("postPage",m,document.getElementById(ifrmId).contentWindow);return true},responseHandler:function(m){var n=m.redirectUrl;if(m.success){var o=n+"?refId="+m.refId+"&success="+m.success+"&signature="+m.signature+"&token="+m.token;window.location.replace(o)}else{var o=n+"?errorCode="+m.errorCode+"&errorMessage="+m.errorMessage+"&success="+m.success+"&signature="+m.signature+"&token="+m.token;window.location.replace(o)}}}}();var ZXD=function(){var e,d,b=1,c,a=this;return{postMessage:function(f,h,g){if(!h){return}g=g||parent;if(a.postMessage){g.postMessage(f,h.replace(/([^:]+:\/\/[^\/]+).*/,"$1"))}else{if(h){g.location=h.replace(/#.*$/,"")+"#"+(+new Date)+(b++)+"&"+f}}},receiveMessage:function(h,g,f){if(a.postMessage){if(h){c=function(l){if(Object.prototype.toString.call(g)==="[object Function]"&&g(l.origin)===!1){return !1}if(typeof g==="string"&&l.origin!==g){if(!f){return !1}else{if(f==="true"){try{if(typeof g==="string"){var i=l.origin.split(".");if(i){var n=i.slice(-2).join(".");var j=g.split(".");var m=j.slice(-2).join(".");if(m.indexOf(n)<=-1){return !1}}}}catch(k){return !1}}else{return !1}}}h(l)}}if(a.addEventListener){a[h?"addEventListener":"removeEventListener"]("message",c,!1)}else{a[h?"attachEvent":"detachEvent"]("onmessage",c)}}else{e&&clearInterval(e);e=null;if(h){e=setInterval(function(){var j=document.location.hash,i=/^#?\d+&/;if(j!==d&&i.test(j)){d=j;h({data:j.replace(i,"")})}},100)}}}}}();var ZFB=function(){var b="yes";var c=navigator.userAgent.substring(navigator.userAgent.indexOf("Firefox")).split("/")[1];var a=parseFloat(c)>=0.1?20:0;return{resizeCaller:function(h,g,d,f){ZFB.resizeIframe(h,g,d,f);if((document.all||document.getElementById)&&b=="no"){var e=document.all?document.all[h]:document.getElementById(h);e.style.display="block"}},resizeIframe:function(f,h,e,g){var d=document.getElementById(f);if(d){d.style.display="block";d.height=Number(e);d.width=Number(g)}}}}();