/*    Copyright (c) 2014 Zuora, Inc.
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy of 
 *   this software and associated documentation files (the "Software"), to use copy, 
 *   modify, merge, publish the Software and to distribute, and sublicense copies of 
 *   the Software, provided no fee is charged for the Software.  In addition the
 *   rights specified above are conditioned upon the following:
 *
 *   The above copyright notice and this permission notice shall be included in all
 *   copies or substantial portions of the Software.
 *
 *   Zuora, Inc. or any other trademarks of Zuora, Inc.  may not be used to endorse
 *   or promote products derived from this Software without specific prior written
 *   permission from Zuora, Inc.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 *   ZUORA, INC. BE LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES
 *   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *   ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
if(console&&console.warn){console.warn("zuora.js v1.2.0 has been deprecated.")}var ifrmId="z_hppm_iframe";if(!String.prototype.trim){(function(){var a=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(a,"")}})()}if(!Object.keys){Object.keys=(function(){var c=Object.prototype.hasOwnProperty,d=!({toString:null}).propertyIsEnumerable("toString"),b=["toString","toLocaleString","valueOf","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","constructor"],a=b.length;return function(g){if(typeof g!=="object"&&(typeof g!=="function"||g===null)){throw new TypeError("Object.keys called on non-object")}var e=[],h,f;for(h in g){if(c.call(g,h)){e.push(h)}}if(d){for(f=0;f<a;f++){if(c.call(g,b[f])){e.push(b[f])}}}return e}}())}(function(){if(!Event.prototype.preventDefault){Event.prototype.preventDefault=function(){this.returnValue=false}}if(!Event.prototype.stopPropagation){Event.prototype.stopPropagation=function(){this.cancelBubble=true}}if(!Element.prototype.addEventListener){var c=[];var b=function(f,h){var d=this;var j=function(k){k.target=k.srcElement;k.currentTarget=d;if(h.handleEvent){h.handleEvent(k)}else{h.call(d,k)}};if(f=="DOMContentLoaded"){var g=function(k){if(document.readyState=="complete"){j(k)}};document.attachEvent("onreadystatechange",g);c.push({object:this,type:f,listener:h,wrapper:g});if(document.readyState=="complete"){var i=new Event();i.srcElement=window;g(i)}}else{if(this.attachEvent){this.attachEvent("on"+f,j)}c.push({object:this,type:f,listener:h,wrapper:j})}};var a=function(f,g){var d=0;while(d<c.length){var e=c[d];if(e.object==this&&e.type==f&&e.listener==g){if(f=="DOMContentLoaded"){this.detachEvent("onreadystatechange",e.wrapper)}else{this.detachEvent("on"+f,e.wrapper)}c.splice(d,1);break}++d}};Element.prototype.addEventListener=b;Element.prototype.removeEventListener=a;if(HTMLDocument){HTMLDocument.prototype.addEventListener=b;HTMLDocument.prototype.removeEventListener=a}if(Window&&Window.prototype){Window.prototype.addEventListener=b;Window.prototype.removeEventListener=a
}}})();var Z=function(){var i="#z-overlay {filter: alpha(opacity=50);opacity:0.5;display:inline-block;position:fixed;top:0;left:0;width:100%;height:100%;background-color: #000;z-index: 1001;}";var f="#z-container {border:1px;float:left; overflow: visible; position: absolute;padding: 0px; display: inline-block; top:5%; left:34%; margin: 0 auto;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius:5px;background-color: #FAFAFA; border:1px solid #FAFAFA;border-top-color:#EDEDED;behavior: url(js/PIE.htc);z-index: 1002;}";var n="#z-data {height: 100%; outline: 0px; width: 100%; overflow: visible;display: inline-block;border:1px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius:5px;}";var k="#reset{*, *:before, *:after {display: inline-block;-webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;}}";var h="#z_hppm_iframe {background-color: #FAFAFA;vertical-align:bottom;z-index:9999;display:block;padding:0px;margin: 0px; border:0px solid #DDD;}";var b="requestPage";var l;var d;var m,g,e;var j=["tenantId","id","token","signature","key","style","submitEnabled","url"];var c=["creditCardNumber","cardSecurityCode","creditCardExpirationYear","creditCardExpirationMonth"];var a=false;return{validateRequiredParams:function(r){var o=j.length;for(index=0;index<o;index++){if(!r.hasOwnProperty(j[index])){if(j[index]=="submitEnabled"&&r.style.toLowerCase()=="overlay"){continue}else{var q="Param with key ["+j[index]+"] is required.";alert(q);if(!Z.isIE()){console.log(q)}return false}}}return true},isIE:function(){var r=window.navigator.userAgent;var q=r.indexOf("MSIE ");var o=r.indexOf("Trident/");if(q>0){return true}if(o>0){var s=r.indexOf("rv:");return true}return false},validatePCIParams:function(s){var o=c.length;for(index=0;index<o;index++){var q="field_"+c[index];if(s.hasOwnProperty(q)){if(0<s[q].trim().length&&s[q].trim().length<300){var r="Field ["+q+"] for Credit Card payment method type should be encrypted for pre-population";alert(r);if(!Z.isIE()){console.log(r)}return false
}}}return true},init:function(t,u){m="?method=requestPage&host="+encodeURIComponent(document.location.href)+"&";m=m+"fromHostedPage=true&";var s=Z.validateRequiredParams(t);if(!s){return false}s=Z.validatePCIParams(t);if(!s){return false}var r=JSON.stringify(t,function(v,w){if(v!=""){if("key"==v){e=w}else{if("url"==v){l=w}else{m=m+v+"="+encodeURIComponent(w)+"&"}}}return w});p=JSON.parse(r);if(!a){ZXD.receiveMessage(function(w){var v=w.data;v=JSON.parse(v);if(v.success){if(u){u(v)}else{Z.responseHandler(v)}}else{if(v.success==false){Z.deactivateOverlay("z-overlay");Z.deactivateOverlay("z-container");u(v)}else{if(v.action=="close"){Z.deactivateOverlay("z-overlay");Z.deactivateOverlay("z-container")}else{if(v.action=="resize"){Z.receive(v)}}}}});a=true}var o=c.length;if(t){for(index=0;index<o;index++){var q="field_"+c[index];if(t.hasOwnProperty(q)){t[q]=""}}}return true},prepopulate:function(r){var s=Z.createIframeURL();if(s==document.getElementById(ifrmId).src||(document.getElementById(ifrmId).src.indexOf(s)>=0&&p.hasOwnProperty("customizeErrorRequired")&&p.customizeErrorRequired=="true")){var o=JSON.stringify(r,function(t,v){if(t!=""){var u="setField("+t+":"+v+")";Z.post(ifrmId,u)}return v});var q="setField(key:"+e+")";Z.post(ifrmId,q);Z.post(ifrmId,"setField(style:"+p.style+")");if(p.hasOwnProperty("customizeErrorRequired")&&p.customizeErrorRequired=="true"){Z.post(ifrmId,"customizeErrorRequired");p.customizeErrorRequired="false"}Z.post(ifrmId,"resize");if(d){d()}}if(d){d=null}},contains:function(o,r){for(var q=0;q<o.length;q++){if(o[q]===r){return true}}return false},renderWithErrorHandler:function(q,s,r,o){q.customizeErrorRequired="true";Z.render(q,s,r);Z.customizeErrorHandler(o)},runAfterRender:function(o){d=o},render:function(t,s,y){var w=c.length;if(s&&s.creditCardCountry&&(s.creditCardCountry==="USA"||s.creditCardCountry==="CAN")){s.creditCardState=s.creditCardState||" "}if(s){for(index=0;index<w;index++){var u="field_"+c[index];if(s.hasOwnProperty(c[index])){t[u]=s[c[index]]}}}var z=Z.init(t,y);if(!z){return
}if(s){var w=Object.keys(s).length;g=s;for(index=0;index<w;index++){var r=Object.keys(s)[index];if(Z.contains(c,r)){delete g[r]}}}else{g=null}var q=document.getElementById("zuora_payment");if(typeof q=="undefined"||!q){return{error:"invalid_request",error_description:"The container you specified does not exist"}}q.innerHTML="";Z.cleanUp(q,"z-overlay");Z.cleanUp(q,"z-container");if(p.style=="inline"){Z.addInlineStyles();Z.createIframe(q);return}if(p.style=="overlay"){Z.addOverlayStyles();var o=Z.generateDiv("z-overlay","z-overlay");q.appendChild(o);var v=Z.generateDiv("z-container","z-container");q.appendChild(v);var x=Z.generateDiv("z-data","z-data");x.tabindex="-1";v.appendChild(x);Z.createIframe(document.getElementById("z-data"));Z.activateOverlay("z-overlay")}},cleanUp:function(q,o){var r=document.getElementById(o);if(r!=null){q.removeChild(r)}},activateOverlay:function(q){try{document.getElementById(q).style.display="inline"}catch(o){}},deactivateOverlay:function(q){try{document.getElementById(q).style.display="none"}catch(o){}},generateDiv:function(s,q,o){var r=document.createElement("div");r.id=s;r.className=q;r.border="0";if(r.addEventListener){r.addEventListener("click",o,false)}else{r.attachEvent("click",o)}return r},addOverlayStyles:function(){var t=document.createElement("style");t.type="text/css";var q=document.createTextNode(i);var u=document.createTextNode(f);var o=document.createTextNode(n);var s=document.createTextNode(h);var r=document.createTextNode(k);if(t.styleSheet){t.styleSheet.cssText=q.nodeValue+" "+u.nodeValue+" "+o.nodeValue+" "+r.nodeValue+" "+s.nodeValue}else{t.appendChild(q);t.appendChild(u);t.appendChild(o);t.appendChild(s);t.appendChild(r)}document.getElementsByTagName("head")[0].appendChild(t)},addInlineStyles:function(){var q=document.createElement("style");q.type="text/css";var o=document.createTextNode(h);if(q.styleSheet){q.styleSheet.cssText=o.nodeValue}else{q.appendChild(o)}document.getElementsByTagName("head")[0].appendChild(q)},createIframe:function(o){var r=Z.createIframeURL();
var q=document.createElement("iframe");q.setAttribute("src",r);q.setAttribute("id",ifrmId);q.setAttribute("overflow","visible");q.setAttribute("scrolling","no");q.setAttribute("frameBorder","0");q.setAttribute("allowtransparency","true");q.setAttribute("class","z_hppm_iframe");q.setAttribute("width","100%");q.setAttribute("height","100%");if(q.addEventListener){q.addEventListener("load",function(s){Z.prepopulate(g);return false},false)}else{q.attachEvent("onload",function(){Z.prepopulate(g);return false})}if(typeof options!="undefined"){if(typeof options.vertical!="undefined"&&options.vertical){q.style.width="100%";q.style.height="100%"}}o.appendChild(q)},createIframeURL:function(){var o=l;return o.concat(m)},post:function(s,r){var o=document.getElementById(s);var q=encodeURIComponent(document.location.href);var t=o.src;if(t.indexOf(q)<=-1){o.src=t+"#"+q}ZXD.postMessage(r,t,o.contentWindow);return false},receive:function(o){ZFB.resizeCaller(ifrmId,o.action,o.height,o.width)},validate:function(r){if(r==null||r==undefined){Z.closeWindow();var q="Validate function required.";alert(q);if(!Z.isIE()){console.log(q)}return false}ZXD.receiveMessage(function(t){var s=t.data;s=JSON.parse(s);r(s)});var o="validate";Z.post(ifrmId,o)},customizeErrorHandler:function(q){if(q==null||q==undefined){Z.closeWindow();var o="Customized error message function required.";alert(o);if(!Z.isIE()){console.log(o)}return false}ZXD.receiveMessage(function(s){var r=s.data;r=JSON.parse(r);if(r.action=="customizeErrorMessage"){q(r.key,r.code,r.message)}})},sendErrorMessageToHpm:function(s,r){var q={action:"customizeErrorMessage",key:s,message:r};var o=JSON.stringify(q);Z.post(ifrmId,o)},closeWindow:function(){Z.deactivateOverlay("z-overlay");Z.deactivateOverlay("z-container")},submit:function(){var o=document.getElementById(ifrmId).src+"#"+encodeURIComponent(document.location.href);document.getElementById(ifrmId).src=o;ZXD.postMessage("postPage",o,document.getElementById(ifrmId).contentWindow);return true},responseHandler:function(o){var q=o.redirectUrl;
if(o.success){var r=q+"?refId="+o.refId+"&success="+o.success+"&signature="+o.signature+"&token="+o.token;window.location.replace(r)}else{var r=q+"?errorCode="+o.errorCode+"&errorMessage="+o.errorMessage+"&success="+o.success+"&signature="+o.signature+"&token="+o.token;window.location.replace(r)}}}}();var ZXD=function(){var e,d,b=1,c,a=this;return{postMessage:function(f,h,g){if(!h){return}g=g||parent;if(a.postMessage){g.postMessage(f,h.replace(/([^:]+:\/\/[^\/]+).*/,"$1"))}else{if(h){g.location=h.replace(/#.*$/,"")+"#"+(+new Date)+(b++)+"&"+f}}},receiveMessage:function(k,j,f){if(a.postMessage){if(k){function h(l){var m=/^https:\/\/([a-z0-9]+(-[a-z0-9]+)*\.)*zuora\.com$/;if(!m.test(l.toLowerCase())){console.info("Stopped processing none-zuora message.");return false}return true}var g=/^https?:\/\/localhost(:\d{4,5})?$/;function i(l){return g.test(l)}c=function(o){if(typeof o.origin==="string"&&!(h(o.origin)||i(o.origin))){return !1}if(Object.prototype.toString.call(j)==="[object Function]"&&j(o.origin)===!1){return !1}if(typeof j==="string"&&o.origin!==j){if(!f){return !1}else{if(f==="true"){try{if(typeof j==="string"){var l=o.origin.split(".");if(l){var r=l.slice(-2).join(".");var m=j.split(".");var q=m.slice(-2).join(".");if(q.indexOf(r)<=-1){return !1}}}}catch(n){return !1}}else{return !1}}}k(o)}}if(a.addEventListener){a[k?"addEventListener":"removeEventListener"]("message",c,!1)}else{a[k?"attachEvent":"detachEvent"]("onmessage",c)}}else{e&&clearInterval(e);e=null;if(k){e=setInterval(function(){var m=document.location.hash,l=/^#?\d+&/;if(m!==d&&l.test(m)){d=m;k({data:m.replace(l,"")})}},100)}}}}}();var ZFB=function(){var b="yes";var c=navigator.userAgent.substring(navigator.userAgent.indexOf("Firefox")).split("/")[1];var a=parseFloat(c)>=0.1?20:0;return{resizeCaller:function(h,g,d,f){ZFB.resizeIframe(h,g,d,f);if((document.all||document.getElementById)&&b=="no"){var e=document.all?document.all[h]:document.getElementById(h);e.style.display="block"}},resizeIframe:function(f,h,e,g){var d=document.getElementById(f);if(d){d.style.display="block";
d.height=Number(e);d.width=Number(g)}}}}();